apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    securityContext:
      privileged: true  
    command: ["sh","-c","sleep 3600000"]
    resources:
      requests:
        cpu: "100m"                        
        memory: "64Mi"                    
        akri.sh/akri-sandisk-conf: "1"    
      limits:
        cpu: "200m"                       
        memory: "128Mi"                  
        akri.sh/akri-sandisk-conf: "1"    
  restartPolicy: Never
 

# Additional Akri USB note for PR16
